@include('emails.layouts.crew', [
    'url' => $url,
    'user' => $user,
    'pageTitle' => '비밀번호 재설정 — PAC RUN CREW',
    'preheader' => '비밀번호 재설정 링크가 도착했습니다. 60분 내에 새 비밀번호를 설정해 주세요.',
    'accent' => '#E80043',
    'heroBg' => '#100A0A',
    'badgeBg' => '#E80043',
    'badgeText' => '#FFFFFF',
    'title2Color' => '#E80043',
    'eyebrowColor' => '#E80043',
    'ctaBg' => '#E80043',
    'ctaText' => '#FFFFFF',
    'ctaBorder' => '#A8002F',
    'urlLabelColor' => '#E80043',
    'urlLinkLabel' => 'RESET LINK',
    'step' => 'SEC',
    'badge' => 'PASSWORD RESET',
    'watermark' => 'R',
    'title1' => '비밀번호',
    'title2' => '재설정 요청',
    'eyebrow' => '비밀번호 재설정 안내',
    'messageHtml' => '비밀번호 재설정 요청이 접수되었습니다.<br>아래 버튼을 클릭하여 새로운 비밀번호를 설정해 주세요.<br>본인이 요청하지 않은 경우 이 메일을 무시하시면 됩니다.',
    'ctaLabel' => '비밀번호 재설정하기',
])
