@include('emails.layouts.crew', [
    'url' => $url,
    'user' => $user,
    'pageTitle' => '이메일 인증 — PAC RUN CREW',
    'preheader' => 'PAC RUN CREW 가입을 환영합니다. 이메일 인증을 완료해 주세요.',
    'accent' => '#E5AD16',
    'heroBg' => '#0F0D0D',
    'badgeBg' => '#E5AD16',
    'badgeText' => '#0F0D0D',
    'title2Color' => '#E5AD16',
    'eyebrowColor' => '#E5AD16',
    'ctaBg' => '#E5AD16',
    'ctaText' => '#0F0D0D',
    'ctaBorder' => '#B8881A',
    'urlLabelColor' => '#E5AD16',
    'urlLinkLabel' => 'DIRECT LINK',
    'step' => '01',
    'badge' => 'EMAIL VERIFICATION',
    'watermark' => 'V',
    'title1' => '이메일',
    'title2' => '인증 요청',
    'eyebrow' => '이메일 인증 안내',
    'messageHtml' => 'PAC RUN CREW에 가입해주셔서 감사합니다.<br>아래 버튼을 클릭하여 이메일 인증을 완료하면<br>모든 서비스를 이용하실 수 있습니다.',
    'ctaLabel' => '이메일 인증하기',
])
